# Generated by Django 2.2.13 on 2022-01-19 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sendplanadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xyz_a',
            name='contact',
        ),
        migrations.AddField(
            model_name='xyz_a',
            name='fname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xyz_a',
            name='lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
