# Generated by Django 2.2.13 on 2022-01-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendplan',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sendplan',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sendplan',
            name='name1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sendplan',
            name='planN',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
